### ISSUE TITLE
Pass through to the Community Repository?

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey-community/simple-server#16]
Allow optional feature to pass through from packages on the community repository. When a package is installed with pass through, a copy of the package will be stored on the local Chocolatey.Server. 

https://github.com/NuGet/NuGetGallery/issues/3004

Also related to #17.

**Comment by ferventcoder** [comment]
This is similar to Proxy repositories that you see with ProGet, Nexus, MyGet, and Artifactory.

**Comment by unquietwiki** [comment]
Okay @ferventcoder , thinking about how this would work...

- I assume we'd want a flag to enable / disable this behavior; as well as to update where the current upstream Chocolatey repo is.
- If there are any plans / tickets that involve having simple-server run standalone (say as a .NET Core 2.0 Kestrel app), then the settings would have to be command-line, or in an INI / YAML / XML file.
- Maybe another flag to determine when to overwrite a local package; or to exclude certain packages from being overwritten (I made my own Windows runtime packages; still need to figure out how to get fixes applied upstream for that sort of thing).
- If the server is acting as a choco-client, then obviously it'll need to know about upstream proxies. This seems totally "meta": but if the server is able to access upstream, but the clients not, then it works?

**Comment by RobBiddle** [comment]
This issue has been open for nearly 5 years. Any chance someone is still working on this? 🤞

**Comment by unquietwiki** [comment]
@RobBiddle I got laid off that same week I posted my last answer, so I apologize for disappearing. None of the environments I've worked on since have needed this, but one or two could've definitely benefited. I can't speak to what @ferventcoder would be dealing with on their end, aside from the announcements I see on the main page.

**Comment by TheCakeIsNaOH** [comment]
This project has not had major development work since about the time this issue was opened, and it is not currently recommended for organizations in most cases. https://docs.chocolatey.org/en-us/guides/organizations/set-up-chocolatey-server#summary

I would definitely suggest checking out Sonatype Nexus, since it has the proxy repository functionality which the same thing as this feature request. Using the [nexus-repository](https://community.chocolatey.org/packages/nexus-repository) package from the Community Repository makes Nexus pretty simple to set up. There is also a video about how to set it up to proxy/pass through the Community Repository: https://www.youtube.com/watch?v=UehkG1VHtz0

**Comment by gep13** [comment]
I agree with @TheCakeIsNaOH here.  There are no plans to actively work on this within the Chocolatey Team.  If a community member wants to pick this up we may be able to assist, but that would be all that could be offered.

As such, I am going to close off this issue.  If anyone is interested, feel free to reply to this issue and we can discuss further.
